### ISSUE TITLE
[OLD] Legacy Mongolian Translation Progress

### ISSUE THREAD

**Issue by tesseralis** [reactjs/mn.react.dev#1]
## Maintainer List

* @dulmandakh
* @zorig
## For New Translators

To translate a page:

1. Check that no one else has claimed your page in the checklist and comments below.
2. Comment below with the name of the page you would like to translate. **Please take only one page at a time**.
3. Clone this repo, translate your page, and submit a pull request!

Before contributing, read the glossary and style guide (once they exist) to understand how to translate various technical and React-specific terms.

Please be prompt with your translations! If you find find that you can't commit any more, let the maintainers know so they can assign the page to someone else.

## For Maintainers

When someone volunteers, edit this issue with the username of the volunteer, and with the PR. Ex:

* [x] Home Page (@tesseralis) #1

When PRs are merged, make sure to mark that page as completed!

## Core Pages

To do before releasing as an "official" translation. **Please translate these pages first.**

* [x] Home Page @zorig #17  
* [x] Tutorial @uuganbold #15 

### Basics

* [x] Hello World @Zorig #29
* [x] Introducing JSX @erdenezul #14 
* [x] Rendering Elements @erdenezul #7
* [x] Components and Props @erdenezul #21 
* [x] State and Lifecycle @zorig #51 
* [x] Handling Events @erdenezul 
* [x] Conditional Rendering @erdenezul #9
* [x] Lists and Keys @erdenezul #4
* [x] Forms @erdenezul #12 
* [x] Lifting State Up @erdenezul #27 
* [x] Composition vs Inheritance @erdenezul #25 
* [x] Thinking in React @erdenezul #20

### API Reference

* [x] React @erdenezul #42 
* [x] React.Component @nominko #75 
* [x] ReactDOM @nominko #70 
* [x] ReactDOMServer @nominko #76 
* [x] DOM Elements @erdenezul  #58 
* [x] SyntheticEvent @nominko #82 
* [x] Test Utilities @nominko #80 
* [x] Shallow Renderer @nominko  #79 
* [x] Test Renderer @nominko #78 
* [x] JS Environment Requirements @nominko #83 
* [x] Glossary @nominko #84

### Navigation

These are the navigation links that appears in the sidebar. Possibly wait until
the corresponding sections are translated to do these.

* [x] tutorial/nav.yml @batbayar-su #43 
* [x] docs/nav.yml @batbayar-su  #43  

## Next Steps

These are the next most important translations, ordered by importance:

### Installation

* [x] Getting Started @batbayar-su #71
* [x] Add React to a Website @batbayar-su #114 
* [x] Create a New React App @batbayar-su #96  
* [x] CDN Links @zorig #64 

### Hooks

Everyone is hooked on hooks! People are really excited for these and it would be great for them to be translated.

  * [x] Introducing Hooks @erdenezul #39
  * [ ] Hooks at a Glance
  * [ ] Using the State Hook
  * [ ] Using the Effect Hook
  * [x] Rules of Hooks @erdenezul  #91 
  * [ ] Building Your Own Hooks
  * [ ] Hooks API Reference
  * [ ] Hooks FAQ

### Warnings

These are the pages that you get when you click the links in the console (e.g. https://reactjs.org/warnings/dont-call-proptypes.html). People tend to search these, so **please don't translate the error message itself**.
 
* [ ] dont-call-proptypes
* [ ] invalid-aria-prop
* [ ] invalid-hook-call-warning
* [ ] legacy-factories
* [ ] refs-must-have-owner
* [ ] special-props
* [ ] unknown-prop

### Advanced Guides

* [ ] Accessibility
* [x] Code-Splitting @erdenezul #36
* [x] Context @rmargaderdene #56 
* [ ] Error Boundaries
* [x] Forwarding Refs @zorig #60
* [x] Fragments @zorig #62 
* [ ] Higher-Order Components @rmargaderdene #57 
* [ ] Integrating with Other Libraries
* [ ] JSX In Depth
* [ ] Optimizing Performance
* [x] Portals #102 @batbayar-su #103 
* [x] React Without ES6 @erdenezul #32 
* [x] React Without JSX @batbayar-su #108 
* [x] Reconciliation @erdenezul #33 
* [ ] Refs and the DOM
* [ ] Render Props
* [ ] Static Type Checking
* [ ] Strict Mode
* [ ] Typechecking With PropTypes
* [X] Uncontrolled Components @erdenezul  #86 
* [ ] Web Components

### FAQ

* [x] APIs and AJAX @batbayar-su #111 
* [ ] Babel, JSX, and Build Steps
* [ ] Passing Functions to Components
* [ ] Component State
* [ ] Styling and CSS
* [ ] File Structure
* [ ] Versioning Policy
* [ ] Virtual DOM and Internals

### Contributing

Priority: Low

* [ ] How to Contribute
* [ ] Codebase Overview
* [ ] Implementation Notes
* [ ] Design Principles

### Components

Components in `src/components` that have some text in them.

* [ ] CodeEditor
* [ ] CodeExample
* [ ] ErrorDecoder
* [ ] LayoutFooter
* [ ] LayoutHeader
* [ ] MarkdownPage

## Additional Translations

These are not the primary translation targets.

* [ ] Blog
* [ ] Community

**Comment by Zorigt0721** [comment]
thank you

**Comment by uuganbold** [comment]
Орчуулга хийхдээ махчлахгүй, ойлгомжтой байдалд нь илүү анхаарна биздээ.

**Comment by dulmandakh** [comment]
Бас хэт нуршуу болгож өөрөө зохиохгүй байхад анхаарвал зүгээр байх

**Comment by dulmandakh** [comment]
@tesseralis hey, could you please check the translation status and if Mongolian is eligible to be listed in https://reactjs.org/languages. On 5th May, we have developers conference, [DevSummit](http://www.devsummit.mn), and I'll give a talk about React as a whole. It would be super cool if we get listed before then. Thank you.

**Comment by tesseralis** [comment]
@dulmandakh It should be listed! It'll be added, under "Needs Contributors". Once 50% of the core pages are translated we can move it to "In Progress" and once the core pages are completed it'll be in the main list! You all are doing fantastic work so far so I don't doubt you'll get there soon :)

**Comment by Zorig** [comment]
@tesseralis thank you so much

**Comment by rmargaderdene** [comment]
@Zorig  Сайна байна уу. Push хийх гэсэн эрх хүрэхгүй байна гээд байх юм?

**Comment by Zorig** [comment]
@rmargaderdene 
1. эхлээд өөртөө clone хийж аваад 
2. тэр дээрээ issue -ны нэрээр branch үүсгэд
3. орчуулгаа хийгээд
4. Pull Request -ыг эх repo-руу үүсгэнэ.

**Comment by rmargaderdene** [comment]
@Zorig thanks. Pull Request үүсгэсэн.

**Comment by Zorig** [comment]
@rmargaderdene үүсгээгүй байна. Pull Request -ыг эх repository-руу үүсгэнэ.

**Comment by Zorig** [comment]
@tesseralis what is the average requirement of getting subdomain? Do we qualified for getting sub domain? and listed as `in progress in` reactjs.org language section?

**Comment by tesseralis** [comment]
@bvaughn usually does it all at once for all the new languages whenever there are new ones. Brian, could you set up the mongolian (mn) subdomain? They're almost done!

**Comment by bvaughn** [comment]
Done.

http://mn.reactjs.org/

**Comment by gaearon** [comment]
Thanks to everyone who contributed to the old website translation!
Started a new issue for the new website: https://github.com/reactjs/mn.react.dev/issues/332
